query($after:String$first:Int!$id:String!$orderBy:PaginationOrderBy!){customView(id: $id){issues(first: $first, after: $after, orderBy: $orderBy){nodes{id,identifier,title,state{id,name},assignee{id,name},priority,updatedAt,createdAt,description,team{id},project{id,name},cycle{id,name,number,startsAt,endsAt,isActive,isFuture,isPast,isNext,isPrevious},dueDate,estimate,projectMilestone{id,name,targetDate,status,project{id}},labels{nodes{id,name,color}},url,branchName,archivedAt,parent{id,identifier,title},children{nodes{id,identifier,title,state{id,name}}}},pageInfo{hasNextPage,endCursor}}}}
