query($id:String!){issue(id: $id){id,identifier,title,state{id,name},assignee{id,name},priority,updatedAt,createdAt,description,team{id},project{id,name},cycle{id,name,number,startsAt,endsAt,isActive,isFuture,isPast,isNext,isPrevious},dueDate,estimate,projectMilestone{id,name,targetDate,status,project{id}},labels{nodes{id,name,color}},url,branchName,archivedAt,parent{id,identifier,title},children{nodes{id,identifier,title,state{id,name}}},relations(first: 50){nodes{id,type,issue{id,identifier,title},relatedIssue{id,identifier,title}}},inverseRelations(first: 50){nodes{id,type,issue{id,identifier,title},relatedIssue{id,identifier,title}}},subscribers(first: 50){nodes{id,name,displayName,email,isMe}},attachments(first: 50){nodes{id,title,subtitle,url,sourceType,createdAt,updatedAt}},comments(first: 100, orderBy: createdAt){nodes{id,body,createdAt,updatedAt,user{id,name,displayName,email,isMe}}}}}
